export default function List() {
    return (
        <div>
            <h2>게시판 페이지</h2>
            <table>
                <thead>
                    <td>번호</td>
                    <td>글제목</td>
                    <td>작성자</td>
                    <td>작성일</td>
                </thead>
                <tr>
                    <td>10</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>9</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>8</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>7</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>테스트글</td>
                    <td>테스트</td>
                    <td>2023.03.20</td>
                </tr>
            </table>
            <div>
                <button>작성하기</button>
            </div>
            <div>
                <button>◁</button>
                <button>1</button>
                <button>2</button>
                <button>3</button>
                <button>4</button>
                <button>5</button>
                <button>6</button>
                <button>7</button>
                <button>8</button>
                <button>9</button>
                <button>10</button>
                <button>▷</button>
            </div>
        </div>
    )
}